### ISSUE TITLE
Got status code 404 when trying to download (KBQA)

### ISSUE THREAD

**Issue by Perevalov** [deeppavlov/explainable_qa#1]
Hi,

I wanted to run your KBQA service, however, faced the following problem during the start of the container:

`RuntimeError: Got status code 404 when trying to download http://files.deeppavlov.ai/tmp/queries_and_rels_lcquad2.tar.gz`

Steps to reproduce:

1. `docker-compose build kbqa`
2. `docker-compose up kbqa`

Thanks in advance!

**Comment by dmitrijeuseew** [comment]
@Perevalov Hi,
I fixed the download link.
I apologize for any inconvenience caused.

**Comment by Perevalov** [comment]
> @Perevalov Hi, I fixed the download link. I apologize for any inconvenience caused.

Thanks @dmitrijeuseew, the process went further, but now another link gives 404: http://files.deeppavlov.ai/tmp/kbqa_files_en.tar.gz

Log:

```
kbqa                      | 2023-07-04 15:00:34,061 - server - ERROR - Got status code 404 when trying to download http://files.deeppavlov.ai/tmp/kbqa_files_en.tar.gz
```

**Comment by dmitrijeuseew** [comment]
@Perevalov I fixed the links, now the service should run without errors.

**Comment by Perevalov** [comment]
> @Perevalov I fixed the links, now the service should run without errors.

Thanks! I'm closing this issue.
